version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.yaml:/home/oncall/config/config.yaml
    networks:
      - iris

  oncall-mysql:
    hostname: oncall-mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=digitaldb
    networks:
      - iris

networks:
  iris:
